variables:
  DOCKER_IMG: "registry.gitlab.com/offa/plug/ci"


build_gcc:
  parallel:
    matrix:
      - COMPILER: gcc
        VERSION: [10, 9, 8, 7]
      - COMPILER: clang
        VERSION: [10, 9, 8, 7, 6]
  image: ${DOCKER_IMG}/$COMPILER-$VERSION:latest
  script:
    - "echo $COMPILER $VERSION"
    - $CC --version
