image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/experimental

services:
  - docker:dind


before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - apk add --update git
  - git clone --depth=1 https://github.com/offa/stm32-eth stm32-eth


gcc-7:
  script:
    - cd stm32-eth
    - ../script/build-image.sh gcc-7 .

gcc-6:
  script:
    - cd stm32-eth
    - ../script/build-image.sh gcc-6 .

clang-5:
  script:
    - cd stm32-eth
    - ../script/build-image.sh clang-5 .

clang-4:
  script:
    - cd stm32-eth
    - ../script/build-image.sh clang-4 .

arm-none-eabi-gcc:
  script:
    - cd stm32-eth
    - ../script/build-image.sh arm-none-eabi-gcc .

