image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}


before_script:
  - docker info
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


gcc-7:
  script:
    - script/build-image.sh gcc-7 docker/x86

gcc-6:
  script:
    - script/build-image.sh gcc-6 docker/x86

clang-5:
  script:
    - script/build-image.sh clang-5 docker/x86

clang-4:
  script:
    - script/build-image.sh clang-4 docker/x86

arm-gcc:
  script:
    - script/build-image.sh gcc-arm docker/arm

