image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMG: "registry.gitlab.com/offa/docker-images/arm-none-eabi-gcc:latest"

services:
  - docker:dind



before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


test:
  image: ${DOCKER_IMG}
  script:
    - arm-none-eabi-gcc --version
    - arm-none-eabi-g++ --version


