image: docker:latest

variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:dind



before_script:
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}


default-job:
  script:
    - echo "Nothing to to ..."

