variables:
  DOCKER_IMG: "registry.gitlab.com/offa/docker-images"


gcc-7:
  image: ${DOCKER_IMG}/gcc-7:latest
  script:
    - script/ci_build.sh

gcc-6:
  image: ${DOCKER_IMG}/gcc-6:latest
  script:
    - script/ci_build.sh

clang-5:
  image: ${DOCKER_IMG}/clang-5:latest
  script:
    - script/ci_build.sh

clang-4:
  image: ${DOCKER_IMG}/clang-4:latest
  script:
    - script/ci_build.sh

