language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPLOY_REGISTRY: ${CI_REGISTRY_IMAGE}/staging-ci-opencv3


matrix:
    include:
    - env: COMPILER=gcc-7
    - env: COMPILER=clang-5


script:
    - IMG=${DEPLOY_REGISTRY}-${COMPILER}
    - cd ci-docker-opencv3
    - docker build --pull -t ${IMG} . --build-arg COMPILER=${COMPILER}
