language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"


matrix:
    include:
    - env: COMPILER=gcc-7
    - env: COMPILER=gcc-6
    - env: COMPILER=clang-5
    - env: COMPILER=clang-4
    - env: COMPILER=arm-none-eabi-gcc


script:
  - echo "Nothing to do at the moment..."
