language: generic

dist: trusty
sudo: required

services:
  - docker


before_install:
  - docker pull agi20dla/cpp-build
  - docker ps -a

script:
  - docker run agi20dla/cpp-build /bin/bash -c "ls"
