language: generic

dist: xenial

matrix:
    include:
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          packages:
            - g++-8
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-xenial-8
            - llvm-toolchain-xenial-7
            - llvm-toolchain-xenial-6.0
            - llvm-toolchain-xenial-5.0
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-3.9
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.6
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: *sources
    - env: CXX=clang++-7 CC=clang-7
      addons:
        apt:
          packages:
            - clang-7
            - libstdc++-7-dev
          sources: *sources
    - env: CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          packages:
            - clang-6.0
          sources: *sources
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
          sources: *sources


script:
  - ${CC} --version
  - ${CXX} --version
  - cmake --version
