language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"

#cache:
  #directories:
    #- ${DEPENDENCY_DIR}


matrix:
    include:
    - env: CC=gcc-7
    - env: CC=gcc-6


before_install:
  - docker pull ${DOCKER_IMG}/${CC}:latest
  - docker images

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/${CC} /bin/bash -c "\${CC} --version"
