language: generic

dist: trusty
sudo: required


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-5.0
            - sourceline: 'ppa:anthony-justsoftwaresolutions/libcxx'
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - libc++-dev
            - libc++
          sources: *sources

script:
  - cmake --version
  - git --version
  - $CC --version
  - $CXX --version
