language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"
    - DOCKER_IMG="registry.gitlab.com/offa/docker-images"

#cache:
  #directories:
    #- ${DEPENDENCY_DIR}


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      #addons:
        #apt:
          #packages:
            #- g++-7
          #sources: &sources
            #- ubuntu-toolchain-r-test
            #- llvm-toolchain-trusty
            #- llvm-toolchain-trusty-5.0
    #- env: CXX=clang++-5.0 CC=clang-5.0
      #addons:
        #apt:
          #packages:
            #- clang-5.0
          #sources: *sources


before_install:
  - docker pull ${DOCKER_IMG}/gcc-7:latest
  - docker images

script:
  - docker run -v ${PWD}:/mnt -it ${DOCKER_IMG}/gcc-7 /bin/bash -c "cd /mnt; pwd; ls"
