language: generic

dist: trusty
sudo: required

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"

cache:
    directories:
        - ${DEPENDENCY_DIR}/gtest

install:
    - mkdir -p "${DEPENDENCY_DIR}" && cd "${DEPENDENCY_DIR}"
    - |
        if [[ ! -d "$(ls -A ${DEPENDENCY_DIR}/gtest)" ]]; then
          GTEST_URL="https://github.com/google/googletest/archive/master.tar.gz"
          mkdir -p gtest && travis_retry wget --no-check-certificate --quiet -O - "${GTEST_URL}" | tar --strip-components=1 -xz -C gtest
        fi
        ls gtest


script:
  - pwd
  - ls
