language: generic

dist: trusty

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"

cache:
    directories:
        - ${DEPENDENCY_DIR}

install:
    - mkdir -p "${DEPENDENCY_DIR}" && cd "${DEPENDENCY_DIR}"
    - |
        if [[ ! -d "$(ls -A ${DEPENDENCY_DIR}/cmake)" ]]; then
          CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.2-Linux-x86_64.tar.gz"
          mkdir -p cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cmake
        fi
        export PATH="${DEPENDENCY_DIR}/cmake/bin:${PATH}"



script:
  - cmake --version
