language: generic

dist: trusty
sudo: required

services:
  - docker

env:
  global:
    - DEPLOY_REGISTRY: registry.gitlab.com/offa/ci-playground/staging-ci-opencv3


script:
  - echo "Nothing to to ..."
