name: "Conan Test"
description: "Test only"
author: "offa"
branding:
  icon: "check-circle"
  color: "green"

runs:
  using: "composite"
  steps:
    - name: "Setup Conan"
      run: |
        apt-get update
        apt-get install -y pipx
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        export PATH="${HOME}/.local/bin:${PATH}"
        pipx install conan
        conan profile detect
      shell: bash
