name: 'Conan Test'
description: 'Test only'
author: 'offa'
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  conan-version:
    description: 'The Conan version use'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup Conan'
      run: |
        apt-get update
        apt-get install -y pipx
        pipx install conan
        conan profile detect
      shell: bash
    - name: 'Test'
      run: |
        pwd
        echo "---"
        ls -la
        echo "---"
      shell: bash
