name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #compiler: [ gcc-9, gcc-8, gcc-7 ]
        config:
          - { name: "Gcc 9", cc: "gcc-9", cxx: "g++-9" }
          - { name: "Gcc 8", cc: "gcc-8", cxx: "g++-8" }
    name: test-${{ matrix.a }}
    steps:
      - uses: actions/checkout@master
      - run: |
         export CC=${{ matrix.config.cc }}
         export CXX=${{ matrix.config.cxx }}
         $CC --version
         $CXX --version
         ls -l
