name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Test"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          VERSION=8
          sudo apt-get install -y clang-${VERSION} libc++-${VERSION}-dev libc++abi-${VERSION}-dev
