name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [ a, b, c ]
        b: [ 1, 2, 3 ]
    name: test-${{ matrix.a }}-${{ matrix.b }}
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "-${{ matrix.a }}-${{ matrix.b }}"
          which gcc
