name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.gitlab.com/offa/plug/ci/gcc-9:latest
    strategy:
      matrix:
        a: [ a, b ]
    name: test-${{ matrix.a }}
    steps:
      - uses: actions/checkout@master
      - run: |
        $CC --version
        cmake --version
