name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler:
          - msvc
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: cmake --version
