name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: echo "<<<${RUNNER_OS}>>>"

  build_osx:
    runs-on: macOs-latest
    steps:
      - uses: actions/checkout@main
      - run: echo "<<<${RUNNER_OS}>>>"

  build_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - run: echo "<<<${RUNNER_OS}>>>"
