name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - arm-none-eabi-gcc-10
    container:
      image: "registry.gitlab.com/offa/docker-images-ci/dist-stm32/${{ matrix.compiler }}:latest"
    name: "${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          ls -l /opt/arm-none-eabi
          arm-none-eabi-gcc --version
          arm-none-eabi-g++ --version
