name: ci

# on: [push, pull_request]
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build_linux:
    runs-on: ubuntu-latest
    name: "Sync test"
    steps:
        uses: jojomatik/sync-branch@v1
        with:
          source: "master"
          target: "to_sync"
          strategy: "fail"
