name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler:
          - gcc-11
          - clang-12
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          export
          python --version
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Build
        run: conan install .


  build_windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler:
          - msvc
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@master
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup MSVC
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Build
        run: conan install .
