name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          echo "<<<${RUNNER_OS}>>>"
          pip3 --version

  build_osx:
    runs-on: macOs-latest
    steps:
      - uses: actions/checkout@main
      - run: |
          echo "<<<${RUNNER_OS}>>>"
          pip3 --version

  build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@main
      - run: |
          echo "<<<${RUNNER_OS}>>>"
          pip3 --version
