name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: "registry.gitlab.com/offa/docker-images/clang:12"
    steps:
      - uses: actions/checkout@main
      - run: ${CXX} --version
      - run: echo "<<<${llvmver}>>>"

