name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 7
          - 8
          #- 9
          #- 10
    name: "${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Install clang
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add
          sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-${{ matrix.version }} main"
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends clang-${{ matrix.version }}
      - name: Install libc++
        run: sudo apt-get install -y --no-install-recommends libc++-${{ matrix.version }}-dev libc++abi-${{ matrix.version }}-dev
