name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 7
    name: "${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Install clang
        run: |
          add-apt-repository ppa:ubuntu-toolchain-r/test
          curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add
          add-apt-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-${{ matrix.version }} main"
          apt-get update
          apt-get install -y --no-install-recommends clang-${{ matrix.version }}
      - name: Install libc++
        run: apt-get install -y --no-install-recommends libc++-${{ matrix.version }}-dev libc++abi-${{ matrix.version }}-dev
