name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-9
          - gcc-8
        boost:
          - true
          - false
    container:
      image: "registry.gitlab.com/offa/plug/docker-images/{{ matrix.compiler }}:stable"


    name: ${{ matrix.compiler }} (Boost: {{ matrix.boost }})
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: echo $CXX
