name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        a: [ 9, 8, 7 ]
    name: test-${{ matrix.a }}
    container: registry.gitlab.com/offa/plug/ci/gcc-${{ matrix.a }}:latest
    steps:
      - uses: actions/checkout@master
      - run: |
        $CC --version
        ls -l
