name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-11
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Test
        env:
          TEST_KEY: ${{ format('TEST_{0}', 'VALUE') }}
        run: echo "<<<${{ TEST_KEY }}>>>"
