name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: gcc:13
    steps:
      - uses: actions/checkout@main
      - run: gcc --version
      - run: uname -a
      - run: lsb_release -a

