name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 6
          - 5
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          echo "deb archive.ubuntu.com/ubuntu xenial main" | sudo tee /etc/apt/sources.list.d/xenial.list
          sudo apt-get update
          sudo apt-get install -y gcc-6
