name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@main
      - run: pacman --version
