name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build"
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@main
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Setup
        run: pip install -r requirements.txt
      - name: oelint-adv
        run: |
          sudo apt-get install -y fd-find
          fdfind --version
