name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc-10
          - gcc-9
          - gcc-8
          - clang-10
          - clang-9
          - clang-8
        boost:
          - true
          - false
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}:stable"
    name: "${{ matrix.compiler }} (Boost: ${{ matrix.boost }})"
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: echo $CXX
