name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 7
          - 8
          - 9
          - 10
          - 11
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.version }}
          gcc-${{ matrix.version }} --version
          g++-${{ matrix.version }} --version
