name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup MSVC
        uses: seanmiddleditch/gha-setup-vsdevenv@master
      - name: Install dependencies
        run: |
          pip install -U conan
          conan install catch2/3.1.0@
