name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value_name:
          - 'VALUE'
    name: "${{ matrix.value_name }}"
    steps:
      - uses: actions/checkout@main
      - name: Test
        env:
          TEST_KEY: ${{ secrets[format('TEST_{0}', 'VALUE')] }}
        run: echo "<<<${TEST_KEY}>>>"
