name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 11
    container:
      image: gcc:${{ matrix.version }}
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          apt-get update
          apt-get install -y gcc-${{ matrix.version }}
          gcc-${{ matrix.version }} --version
