name: ci

on:
  push:
    branches:

permissions:
  contents: write

jobs:
  build_linux:
    runs-on: windows-latest
    name: "Test"
    steps:
      - uses: actions/checkout@main
      - name: Setup Ninja
        uses: turtlesec-no/get-ninja@main
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: ./setup.sh
        shell: bash
      - name: Build
        run: ./test.sh
        shell: bash
