name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [gcc-9, gcc-8]
    name: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@master
      - run: |
        echo {{ martrix.compiler }}
