name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 6
          #- 5
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          echo "deb http://old-releases.ubuntu.com/ubuntu zesty main" | sudo tee /etc/apt/sources.list.d/zesty.list
          sudo apt-add-repository -r universe
          sudo apt-get update
          sudo apt-get install -y gcc-6
