name: ci

on:
  push:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        img:
          - docker.io/fedora:39
          - docker.io/archlinux
          - docker.io/ubuntu:22.04
          - docker.io/debian:debian:bookworm
    name: "Test"
    steps:
      - name: Test
        run: cat /etc/security/faillock.conf | grep "deny =" 
