name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 11
          - 10
          - 9
          - 8
          - 7
          - '6.0'
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          sudo ./ci_install_clang.sh ${{ matrix.version }}
      - name: Test
        run: |
          clang-${{ matrix.version }} --version
