name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 16, 17 ]
    name: jdk-${{ matrix.java }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup jdk-${{ matrix.java }}
        uses: actions/setup-java@main
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Test
        run: java -version
