name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    container:
      image: python:${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@main        
    - name: Test
      run: |
        python --version
        echo "---"
        whoami
        echo "---"
        pwd
        echo "---"
        id