name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ABC: 123
    steps:
      - name: step 1
        run: echo "<<<$ABC>>>"
      - name: step 2
        run: pwd
      - name: step 3
        run: ls -lh
