name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ABC: 123
    steps:
      - uses: actions/checkout@master
      - name: build 1
        run: echo "<<<$ABC>>>"
      - name: build 2
        run: pwd
      - name: build 3
        run: ls -lh
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test 1
        run: uname -a
      - name: test 2
        run: cat /etc/lsb-release
