name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.version }}
    steps:
      - uses: actions/checkout@main
      - name: Install Ninja
        uses: offa/get-ninja@deprecation
        id: step1

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "<<<${{needs.build.outputs.output1}}>>>"
