name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 6
          - 5
    container:
      image: gcc:${{ matrix.version }}
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          apt-get update
          apt-get install -y cmake
          gcc --version
          cmake --version
          #echo "deb http://archive.ubuntu.com/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/bionic_main.list
          #echo "deb http://archive.ubuntu.com/ubuntu bionic universe" | sudo tee /etc/apt/sources.list.d/bionic_universe.list
          #sudo apt-get update
          #sudo apt-get install -y gcc-${{ matrix.version }}
          #gcc-${{ matrix.version }} --version
