name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version:
          - 10
    container:
      image: gcc:${{ matrix.version }}
    name: "Test ${{ matrix.version }}"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          apt-get update
          apt-get install -y cmake
          gcc --version
          cmake --version

  build_test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          pip --version
          pip3 --version
