name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: "Test"
    steps:
      - uses: actions/checkout@master
      - name: Test
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install gcc-6
