name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    container:
      image: ghcr.io/jhnc-oss/images/python:${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@main        
    - name: Test
      run: python --version
