name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    container:
      image: "registry.gitlab.com/offa/docker-images/gcc:12"
    steps:
      - uses: actions/checkout@main
      - run: gcc-12 --version
      - run: apt-get update

